config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "orders#index"

  resources :orders, only: [:index, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/discount.rb
class Discount < ApplicationRecord

  validates :name, presence: true, uniqueness: true
  validates :deduction_in_percent, presence: true, numericality: { greater_than_or_equal_to: 0 }

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

end

app/models/order.rb
class Order < ApplicationRecord

  enum state: %w[OPEN COMPLETED]

  validates :state, presence: true, inclusion: { in: states.keys }

  has_many :order_items, dependent: :destroy
  has_and_belongs_to_many :promotions
  belongs_to :discount, optional: true

  # Currently the order total is calculated on the fly in memory which is sufficient in our scenario but we can also persist
  # this value in the DB by calculating it in an after_create/after_update callback depending on use case.
  def total_price
    apply_promotions
    sum = order_items_sum
    price_after_discount(sum)
  end

  def promotion_codes
    promotions.present? ? promotions.pluck(:name).join(", ") : "-"
  end

  def discount_code
    discount&.name || "-"
  end

  private

  def apply_promotions
    order_items_hash = order_items.group_by { |item| [item.pizza_id, item.size] }

    promotions.each do |p|
      target_pizzas = order_items_hash[[p.target_pizza_id, p.target_size]] || []

      if target_pizzas.size >= p.from
        free_pizzas_count = (p.from - p.to) * multiple(target_pizzas.count, p.from)
        target_pizzas.first(free_pizzas_count).each do |item|
          item.free = true
        end
      end
    end
  end

  def order_items_sum
    sum = 0

    order_items.each do |i|
      price = !i.free ? i.pizza.price * Pizza::SIZE_MULTIPLIERS[i.size] : 0
      price += i.added_ingredients.pluck(:price).sum * Pizza::SIZE_MULTIPLIERS[i.size]
      sum += price
    end
    sum
  end

  def price_after_discount(price)
    return price unless discount.present?

    (price - (discount.deduction_in_percent / 100 * price))
  end

  def multiple(number1, number2)
    number1 % number2 == 0 ? number1 / number2 : 1
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  attr_accessor :free
  after_initialize :set_free

  belongs_to :order
  belongs_to :pizza

  validates :size, presence: true, inclusion: { in: Pizza::PIZZA_SIZES }

  def name
    pizza.name
  end

  def added_ingredients
    ingredients(add)
  end

  def removed_ingredients
    ingredients(remove)
  end

  private

  def set_free
    self.free = false
  end

  def ingredients(ids)
    Ingredient.where(id: ids)
  end

end

app/models/pizza.rb
class Pizza < ApplicationRecord

  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  PIZZA_SIZES = %w[Small Medium Large].freeze

  SIZE_MULTIPLIERS = {
    'Small' => 0.7,
    'Medium' => 1,
    'Large' => 1.3
  }.freeze

end

app/models/promotion.rb
class Promotion < ApplicationRecord

  has_and_belongs_to_many :orders
  belongs_to :target_pizza, class_name: 'Pizza', foreign_key: 'target_pizza_id'
  enum target_size: %w[Small Medium Large]

  validates :name, presence: true, uniqueness: true
  validates :from, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :to, presence: true, numericality: { greater_than_or_equal_to: 1 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.OPEN
  end

  def update
    order = Order.find_by(uuid: params[:id])
    if order.update(state: 1)
      # flash messages haven't been implemented in this project but this is how the update method should behave ideally.
      flash[:success] = "Order marked as completed"
    else
      flash[:error] = order.errors.full_messages.to_sentence
    end
    redirect_to request.referer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

  def price_in_euros(price)
    number_with_precision(price, precision: 2) + "€"
  end

  def display_datetime(datetime)
    datetime.strftime('%B %-d, %Y %H:%M')
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PizzaStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Orders</h1>
<hr>
<% @orders.each do |order| %>
  <div class="row order">
    <div class="col-6">
      <p>ID: <%= order.uuid %></p>
      <p>Created: <%= display_datetime(order.created_at) %></p>
      <p>Promotion Codes: <%= order.promotion_codes %></p>
      <p>Discount Codes: <%= order.discount_code %></p>
      <p>Total Price: <%= price_in_euros(order.total_price) %></p>
      <p>
        <%= button_to 'Complete', order_path(order.uuid), { method: :patch } %>
      </p>
    </div>
    <div class="col-6">
      <p>Items</p>
      <ul>
        <% order.order_items.each do |order_item| %>
          <li>
            <%= order_item.name %> (<%= order_item.size %>)
            <% if order_item.add.present? %>
              <ul>
                <li>
                  Add: <%= order_item.added_ingredients.pluck(:name).join(", ") %></li>
              </ul>
            <% end %>
            <% if order_item.remove.present? %>
              <ul>
                <li>
                  Remove: <%= order_item.removed_ingredients.pluck(:name).join(", ") %></li>
              </ul>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <hr>
<% end %>